<h4 align="justify"><strong>Software Disclaimer</strong></h4>
<p align="justify">
  End User License Agreement: <br />
  IMPORTANT -- READ CAREFULLY BEFORE  DOWNLOADING, INSTALLING, OPENING SOFTWARE PACKET(S) AND/OR USING THE SOFTWARE.  BY DOWNLOADING, OPENING THE SEALED PACKET(S) CONTAINING THE SOFTWARE AND/OR  USING THE SOFTWARE, YOU INDICATE YOUR ACCEPTANCE OF THE FOLLOWING SOFTWARE  LICENSE AGREEMENT AND ANY OTHER ASSOCIATED DOCUMENTATION. </p>
<p align="justify"><br />
  <strong>Click on &quot;I AGREE – Install  Software&quot; at the bottom of the page if you agree with this license.  Otherwise click on I DO NOT AGREE to close this page.</strong> </p>
<p align="justify"><br />
  USER SOFTWARE LICENSE AGREEMENT <br />
  This software license agreement,  including any additional provisions set forth in any other associated  documentation, is a legal agreement between you (either an individual or an  entity) and Lucky Connections Inc. (&quot;Lc&quot;). By downloading/opening/installing  the sealed software packet(s) and/or using the software, you are agreeing to be  bound by the terms of this agreement. If you do not agree to the terms of this  agreement, promptly return the unopened software packet(s) and the accompanying  items (including any hardware, written materials, and binders or other  containers) to the place you obtained them for a full refund. </p>
<p align="justify"><br />
  1. GRANT OF LICENSE. This License  Agreement permits you to use one copy of the software program(s) included in  this package (the &quot;SOFTWARE&quot;) on a single computer. The SOFTWARE is  in &quot;use&quot; on a computer when it is loaded into temporary memory (i.e.  RAM) or installed into permanent memory (e.g., hard disk, CD-ROM, or other  storage device) of that computer. However, installation on a network server for  the sole purpose of internal distribution shall not constitute &quot;use&quot;  for which a separate license is required, provided you have a separate license  for each computer to which the SOFTWARE is distributed. If the SOFTWARE is not  accompanied by a new computer system, you may not use or copy the SOFTWARE. </p>
<p align="justify"><br />
  2. COPYRIGHT. The SOFTWARE  (including any images, &quot;applets&quot;, photographs, animations, video,  audio, music and text incorporated into the SOFTWARE) is owned by Lc or it  licensors and is protected by United States copyright an/or patent laws and  international treaty provisions and all other applicable national laws. All  rights are reserved. Therefore, you must treat the SOFTWARE like any other  copyrighted material (e.g., a book or musical recording) except that if the  SOFTWARE is not copy protected you may either (a) make one copy of the SOFTWARE  solely for backup or archival purposes, or (b) transfer the SOFTWARE to a  single hard disk provided you keep the original solely for backup or archival  purposes. You may not copy the user documentation accompanying the SOFTWARE. </p>
<p align="justify"><br />
  3. SOFTWARE MEDIA. You may receive  the SOFTWARE in disk media, or on a CD-ROM, or installed on the hard disk drive  or ROM of your computer, or in multiple forms of media. Regardless of the  number or type(s) of media you receive, you may use only the media appropriate  for your single computer. You may not use the other media on another computer  or load, rent, lease, or transfer them to another user except as part of the  permanent transfer (as provided below) of all SOFTWARE and user documentation. </p>
<p align="justify"><br />
  4. OTHER RESTRICTIONS. You may not  rent or lease the SOFTWARE, but you may transfer the SOFTWARE on a permanent  basis provided you retain no copies and the recipient agrees to the terms of  this Agreement. If the SOFTWARE is an update or has been updated, any transfer  must include the most recent update and all prior versions. To the maximum  extent permitted by applicable law, you may not reverse engineer, decompile, or  disassemble the SOFTWARE. </p>
<p align="justify"><br />
  5. U.S. GOVERNMENT RESTRICTED  RIGHTS. The SOFTWARE is provided with RESTRICTED RIGHTS. Use, duplication, or  disclosure by the United States Government is subject to restrictions as set  forth in subparagraph (c)(1)(ii) of the Rights in Technical Data and Computer  Software clause at DFARS 252.227-7013 or subparagraphs (c)(1) and (2) of the  Commercial Computer Software -- Restricted Rights at 48 CFR 52.227-19, as  applicable. Manufacturer is Lucky Connections Inc., 2 Niven Street-ON | CA, or  its suppliers. </p>
<p align="justify"><br />
  6. TRADEMARK. The trademarks  contained in the SOFTWARE are owned by their respective owners. No right,  license, or interest to such trademark is granted hereunder, and you agree that  no such right, license, or interest shall be asserted by you with respect to  such trademarks. </p>
<p align="justify"><br />
  7. SUPPORT. For product support,  please refer to Lc’s support number provided in the documentation for the  SOFTWARE or for your computer. Should you have any questions concerning this  Agreement, or if you desire to contact Lc for any other reason, please refer to  the address provided in the documentation for your computer. </p>
<p align="justify"><br />
  8. LIMITED WARRANTY. THE SOFTWARE IS  DISTRIBUTED AND LICENSED &quot;AS IS&quot;, WITH NO WARRANTIES WHATSOEVER,  EXPRESS OR IMPLIED. LC WARRANTS THAT THE MEDIA CONTAINING THE SOFTWARE IS FREE  FROM DEFECTS IN MATERIALS AND WORKMANSHIP FOR A PERIOD OF SIXTY (60) DAYS AFTER  RECEIPT BY YOU. ANY HARDWARE ACCOMPANYING THE SOFTWARE SHALL BE WARRANTED  PURSUANT TO LC's THEN-CURRENT HARDWARE LIMITED WARRANTY. SOME  STATES/JURISDICTIONS DO NOT ALLOW LIMITATIONS ON DURATION OF AN IMPLIED  WARRANTY, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU. DUE TO THE COMPLEX  NATURE OF COMPUTER SOFTWARE, LC AND ITS LICENSORS DO NOT WARRANT THAT THE  SOFTWARE IS COMPLETELY ERROR FREE, WILL OPERATE WITHOUT INTERRUPTION, OR IS  COMPATIBLE WITH ALL EQUIPMENT AND SOFTWARE CONFIGURATIONS. YOU EXPRESSLY ASSUME  ALL RISK FOR USE OF THE PROGRAM. CUSTOMER REMEDIES. LC's and its licensors'  entire liability and your exclusive remedy shall be, at Lc's option, either (a)  return of the actual price paid by you for the SOFTWARE, or (b) repair or replacement  of the media that does not meet this Limited Warranty and which is returned to LC  with a copy of your receipt. This Limited Warranty is void if failure has  resulted from accident, abuse, misuse or misapplication. Any replacement media  will be warranted for the remainder of the original warranty period or thirty  (30) days, whichever is longer. </p>
<p align="justify"><br />
  9. NO OTHER WARRANTIES. TO THE  MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, LC AND ITS LICENSORS DISCLAIM ALL  OTHER WARRANTIES, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE,  WITH REGARD TO THE SOFTWARE. IMPLIED WARRANTIES, IF ANY, ON THE SOFTWARE ARE  LIMITED TO THIRTY (30) DAYS. THIS LIMITED WARRANTY GIVES YOU SPECIFIC LEGAL  RIGHTS. YOU MAY HAVE OTHERS WHICH VARY FROM STATE/JURISDICTION TO  STATE/JURISDICTION. </p>
<p align="justify"><br />
  10. NO LIABILITY FOR CONSEQUENTIAL  DAMAGES. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL LC  OR ITS LICENSORS BE LIABLE FOR ANY CONSEQUENTIAL, RELIANCE, INCIDENTAL,  SPECIAL, DIRECT OR INDIRECT DAMAGES WHATSOEVER (INCLUDING WITHOUT LIMITATION,  DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS  INFORMATION, PERSONAL INJURY, OR ANY OTHER LOSS WHETHER FOR CONTRACT, TORT, STRICT  LIABILITY OR OTHERWISE) ARISING OUT OF OR IN CONNECTION WITH THE USE OF OR  INABILITY TO USE THIS PRODUCT, EVEN IF LC OR ITS SUPPLIERS HAVE BEEN ADVISED OF  THE POSSIBILITY OF SUCH DAMAGES. IN ANY CASE, LC'S AND ITS LICENSORS' ENTIRE  LIABILITY UNDER ANY PROVISION OF THIS AGREEMENT SHALL BE LIMITED TO THE AMOUNT  ACTUALLY PAID BY YOU FOR THE SOFTWARE. BECAUSE SOME STATES/JURISDICTIONS DO NOT  ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL  DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. </p>
<p align="justify"><br />
  11. GOVERNING LAW AND SEVERABILITY.  This Software License Agreement and Limited Warranty are governed by the laws  of the State of California, U.S.A. In the event that any of the provisions of  this Agreement or the application of any such provisions to the parties hereto  with respect to their obligations hereunder shall be held by a court of  competent jurisdiction to be unlawful or unenforceable, the remaining  provisions of this Agreement shall remain in full force and effect, and shall  not be affected, impaired, or invalidated in any manner. </p>

